############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Blog"
url = "/blog"
weight = 2


[[main]]
name = "Acerca de"
url = "/about"
weight = 3


# footer menu
[[footer]]
name = "Acerca de"
url = "/about"
weight = 1

[[footer]]
name = "Blog"
url = "/blog"
weight = 2

[[footer]]
name = "Política de privacidad"
url = "/privacy-policy"
weight = 3
